<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-LOH3IH4" failures="1" tests="1" name="Default test(failed)" time="4.48" errors="0" timestamp="2023-11-01T15:39:07 IST">
  <testcase classname="api.customer.tests.CartTests" name="verifyCreateCart" time="4.059">
    <failure type="java.lang.AssertionError" message="order Number is not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: order Number is not found expected [true] but found [false]
at api.customer.tests.CartTests.verifyCreateCart(CartTests.java:115)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyCreateCart -->
  <testcase classname="api.customer.tests.CartTests" name="verifyTheProductIsNotAddedInCartWityNegativeQuantity" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTheProductIsNotAddedInCartWityNegativeQuantity -->
</testsuite> <!-- Default test(failed) -->
